// <auto-generated />
using System;
using FashionERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FashionERP.Migrations
{
    [DbContext(typeof(FashionStoreERPContext))]
    [Migration("20251116223615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FashionERP.Models.Entities.ChiTietDonHang", b =>
                {
                    b.Property<string>("Ma_DonHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ma_SanPham")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.HasKey("Ma_DonHang", "Ma_SanPham");

                    b.HasIndex("Ma_SanPham");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.ChiTietGioHang", b =>
                {
                    b.Property<string>("Ma_GioHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ma_SanPham")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.HasKey("Ma_GioHang", "Ma_SanPham");

                    b.HasIndex("Ma_SanPham");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.DanhMuc", b =>
                {
                    b.Property<string>("Ma_DanhMuc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ma_DanhMucCha")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten_DanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Ma_DanhMuc");

                    b.HasIndex("Ma_DanhMucCha");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Ma_DanhMuc = "NAM",
                            Ten_DanhMuc = "Thời trang nam",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "NU",
                            Ten_DanhMuc = "Thời trang nữ",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "UNI",
                            Ten_DanhMuc = "Unisex",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "PK",
                            Ten_DanhMuc = "Phụ kiện",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "NAM_AT",
                            Ma_DanhMucCha = "NAM",
                            Ten_DanhMuc = "Áo thun nam",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "NAM_SM",
                            Ma_DanhMucCha = "NAM",
                            Ten_DanhMuc = "Áo sơ mi nam",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "NAM_QS",
                            Ma_DanhMucCha = "NAM",
                            Ten_DanhMuc = "Quần short nam",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "NU_VAY",
                            Ma_DanhMucCha = "NU",
                            Ten_DanhMuc = "Váy nữ",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "NU_DAM",
                            Ma_DanhMucCha = "NU",
                            Ten_DanhMuc = "Đầm nữ",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "NU_AT",
                            Ma_DanhMucCha = "NU",
                            Ten_DanhMuc = "Áo thun nữ",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "UNI_AT",
                            Ma_DanhMucCha = "UNI",
                            Ten_DanhMuc = "Áo thun Unisex",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "UNI_HOOD",
                            Ma_DanhMucCha = "UNI",
                            Ten_DanhMuc = "Áo Hoodie Unisex",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "PK_NON",
                            Ma_DanhMucCha = "PK",
                            Ten_DanhMuc = "Nón",
                            Trang_Thai = true
                        },
                        new
                        {
                            Ma_DanhMuc = "PK_TUI",
                            Ma_DanhMucCha = "PK",
                            Ten_DanhMuc = "Túi xách",
                            Trang_Thai = true
                        });
                });

            modelBuilder.Entity("FashionERP.Models.Entities.DonHang", b =>
                {
                    b.Property<string>("Ma_DonHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ma_KhachHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ma_PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ma_Voucher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Ngay_Dat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tong_Tien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Trang_Thai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ma_DonHang");

                    b.HasIndex("Ma_KhachHang");

                    b.HasIndex("Ma_PhuongThuc");

                    b.HasIndex("Ma_Voucher");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.GioHang", b =>
                {
                    b.Property<string>("Ma_GioHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ma_KhachHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Ma_GioHang");

                    b.HasIndex("Ma_KhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.HinhAnhSanPham", b =>
                {
                    b.Property<int>("Ma_HinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma_HinhAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ma_SanPham")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Ma_HinhAnh");

                    b.HasIndex("Ma_SanPham");

                    b.ToTable("HinhAnhSanPhams");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.KhachHang", b =>
                {
                    b.Property<string>("Ma_KhachHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Hinh_Anh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ma_TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Ma_KhachHang");

                    b.HasIndex("Ma_TaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.NhanVien", b =>
                {
                    b.Property<string>("Ma_NhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Hinh_Anh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ma_TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Ma_NhanVien");

                    b.HasIndex("Ma_TaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<string>("Ma_PhuongThuc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Ten_PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ma_PhuongThuc");

                    b.ToTable("PhuongThucThanhToans");

                    b.HasData(
                        new
                        {
                            Ma_PhuongThuc = "TT-KNH",
                            Ten_PhuongThuc = "Thanh toán khi nhận hàng"
                        },
                        new
                        {
                            Ma_PhuongThuc = "TT-CKNH",
                            Ten_PhuongThuc = "Chuyển khoản ngân hàng"
                        },
                        new
                        {
                            Ma_PhuongThuc = "TT-VDT",
                            Ten_PhuongThuc = "Ví điện tử"
                        });
                });

            modelBuilder.Entity("FashionERP.Models.Entities.SanPham", b =>
                {
                    b.Property<string>("Ma_SanPham")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Gia_Giam")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kich_Thuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ma_DanhMuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mau_Sac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mo_Ta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.Property<string>("Ten_SanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Ma_SanPham");

                    b.HasIndex("Ma_DanhMuc");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("Ma_TaiKhoan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Da_XacThuc")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Han_XacThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ma_VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ma_XacThuc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mat_Khau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten_DangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Ma_TaiKhoan");

                    b.HasIndex("Ma_VaiTro");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.VaiTro", b =>
                {
                    b.Property<string>("Ma_VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten_VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Ma_VaiTro");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.Voucher", b =>
                {
                    b.Property<string>("Ma_Voucher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GiaTri_ToiThieu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Giam_PhanTram")
                        .HasColumnType("int");

                    b.Property<decimal?>("Giam_Tien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Ngay_BatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngay_KetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("So_LanDung")
                        .HasColumnType("int");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Ma_Voucher");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Ma_DonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionERP.Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("Ma_SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.ChiTietGioHang", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("Ma_GioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionERP.Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("Ma_SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.DanhMuc", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.DanhMuc", "DanhMucCha")
                        .WithMany("DanhMucCon")
                        .HasForeignKey("Ma_DanhMucCha");

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.DonHang", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("Ma_KhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FashionERP.Models.Entities.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("DonHangs")
                        .HasForeignKey("Ma_PhuongThuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FashionERP.Models.Entities.Voucher", "Voucher")
                        .WithMany("DonHangs")
                        .HasForeignKey("Ma_Voucher");

                    b.Navigation("KhachHang");

                    b.Navigation("PhuongThucThanhToan");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.GioHang", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("GioHangs")
                        .HasForeignKey("Ma_KhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.HinhAnhSanPham", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.SanPham", "SanPham")
                        .WithMany("HinhAnhSanPhams")
                        .HasForeignKey("Ma_SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("FashionERP.Models.Entities.KhachHang", "Ma_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("FashionERP.Models.Entities.NhanVien", "Ma_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.SanPham", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("Ma_DanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("FashionERP.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("Ma_VaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.DanhMuc", b =>
                {
                    b.Navigation("DanhMucCon");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("HinhAnhSanPhams");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("FashionERP.Models.Entities.Voucher", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
